
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_authorisation
    username: postgres
    password:  Shikha@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

base:
  url: "http://localhost:8080"